# Generated by Django 3.0.6 on 2020-05-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('sku', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('is_active', models.BooleanField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('path', models.CharField(default=None, max_length=500)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('path', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
