# Generated by Django 3.0.6 on 2020-05-17 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200516_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
