# Generated by Django 3.0.6 on 2020-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webhookmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookmodel',
            name='is_active',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='productuploadmodel',
            name='path',
            field=models.FileField(upload_to='csvs/%Y/%m/%d/'),
        ),
    ]
