# Generated by Django 3.0.6 on 2020-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200517_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploadmodel',
            old_name='total_rows',
            new_name='size',
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='status',
            field=models.CharField(default='Queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='productuploadmodel',
            name='path',
            field=models.FileField(upload_to='csvs/%Y/%m/%d/', verbose_name='Document'),
        ),
    ]
