# Generated by Django 3.0.6 on 2020-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200517_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookmodel',
            name='path',
            field=models.URLField(default=None, max_length=500),
        ),
    ]
