# Generated by Django 3.0.6 on 2020-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200517_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookmodel',
            name='path',
        ),
        migrations.AddField(
            model_name='webhookmodel',
            name='url',
            field=models.URLField(default=None, max_length=500, verbose_name='URL'),
        ),
    ]
